#!/bin/bash

DIR='C:\Users\kaybean\Documents\UNC-Senior\COMP562\Final_Project\data\Dataset_BUSI_with_GT'

TARGET_DIR='C:\Users\kaybean\Documents\UNC-Senior\COMP562\Final_Project\data\Dataset_BUSI_with_GT_no_masks'

mkdir "$TARGET_DIR"
cp -R "$DIR"/* "$TARGET_DIR"

for dir in "$TARGET_DIR"/*/; do
    for file in "$dir"*_mask*; do
        rm "$file"
    done
done