#!/bin/bash

DIR='C:\Users\ilpie\Desktop\Fall 2021\Comp 562\Comp562-Final-Project\data\Dataset_BUSI_with_GT'

TARGET_DIR='C:\Users\ilpie\Desktop\Fall 2021\Comp 562\Comp562-Final-Project\data\Dataset_BUSI_with_GT_no_masks'

mkdir "$TARGET_DIR"
cp -R "$DIR"/* "$TARGET_DIR"

for dir in "$TARGET_DIR"/*/; do
    for file in "$dir"*_mask*; do
        rm "$file"
    done
done